#!/bin/bash

timestamp=$(date +%s)
savepath=$HOME/Pictures/

while getopts "h-:" opt; do
	if [[ "$opt" == "-" ]]; then
		opt=$OPTARG;
	fi;
	case $opt in
		s|selection)
			import -quality 0 "${savepath}/${timestamp}.png"
			exit 0
			;;
		w|window)
			import -window root -quality 0 "${savepath}/${timestamp}.png"
			exit 0
			;;
		*)
			echo "Invalid option"
			exit 1
			;;
	esac
done
